# scripts/call_colab.py
# PURPOSE:
# Execute Open University video renderer notebook non-interactively
# using papermill, producing final.mp4 and artifacts

import sys
import subprocess
import os
from pathlib import Path

# ==============================
# PATHS (repo-root relative)
# ==============================

BASE_DIR = Path(__file__).resolve().parent.parent

NOTEBOOK = BASE_DIR / "open_university_video_renderer.ipynb"
OUTPUT_NOTEBOOK = BASE_DIR / "executed_open_university_video_renderer.ipynb"

SLIDE_PLAN = BASE_DIR / "slide_plan.json"
AUDIO_MAP = BASE_DIR / "slide_audio_map.json"

# ==============================
# MAIN
# ==============================

def main():
    # --------------------------
    # HARD VALIDATION
    # --------------------------

    for f in [NOTEBOOK, SLIDE_PLAN, AUDIO_MAP]:
        if not f.exists():
            print(f"ERROR: Required file missing: {f}")
            sys.exit(1)

    print("✔ Required inputs found")
    print("Executing renderer notebook via papermill...")

    # --------------------------
    # ENV REQUIRED BY NOTEBOOK
    # --------------------------

    env = os.environ.copy()
    env["PHONEMIZER_ESPEAK_PATH"] = "/usr/lib/x86_64-linux-gnu/libespeak-ng.so.1"
    env["ESPEAK_PATH"] = "/usr/lib/x86_64-linux-gnu/libespeak-ng.so.1"

    # --------------------------
    # PAPERMILL EXECUTION
    # --------------------------

    cmd = [
        sys.executable,
        "-m",
        "papermill",
        str(NOTEBOOK),
        str(OUTPUT_NOTEBOOK),
        "-p", "SLIDE_PLAN_PATH", "slide_plan.json",
        "-p", "AUDIO_MAP_PATH", "slide_audio_map.json",
    ]

    subprocess.run(
        cmd,
        cwd=str(BASE_DIR),
        env=env,
        check=True,
    )

    # --------------------------
    # POST-CHECK
    # --------------------------

    final_video = BASE_DIR / "final.mp4"
    if not final_video.exists():
        print("ERROR: final.mp4 not generated by renderer")
        sys.exit(1)

    print("✔ Notebook executed successfully")
    print("✔ final.mp4 generated")
    print("✔ Coursera-grade video pipeline complete")


if __name__ == "__main__":
    main()
