name: Test Kaggle API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Kaggle CLI
        run: |
          pip install kaggle

      - name: Run Kaggle test
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          python test_kaggle.py
